### ISSUE TITLE
Implement central saving of all experimental parameters

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#119]
This is useful for saving metadata.

**Comment by mkbhaskar** [comment]
this is now possible with the `log.update_metadata(**metadata)` command which streams the metadata as a pickled dictionary (so metadata must be pickle-able) to the `LogService`. Any client can then access this dictionary with `log.get_metadata()`, or can use the helper function `save_metadata(log, filename, directory, date_dir)` to save it to a .json file

All we need to do is add the `log.update_metadata` command in strategic places where we actually want metadata to be saved (rather than just default saving everything, which can become overwhelming)
