### ISSUE TITLE
Zero-gaps in digital pulse sequences yields unexpected exception

### ISSUE THREAD

**Issue by cknaut** [lukingroup/pylabnet#236]
Zero-gaps in digital pulse sequences yields unexpected exception

![image](https://user-images.githubusercontent.com/4958226/122781839-32819f00-d27e-11eb-807e-58ad27fca3cd.png)

If the above value of Toptica `t0` is changed from 0.1 to 0, the following exception occurs:

![image](https://user-images.githubusercontent.com/4958226/122782007-57761200-d27e-11eb-9846-9c6c8584b039.png)

**Comment by cknaut** [comment]
This has been patched by changing 

```python
      # Sanity check that both methods should give the same length
        if not len(codeword_times) == len(codeword_times_force_value):
            self.log.error(codeword_times)
            self.log.error(codeword_times_force_value)
            self.log.error(codewords[265:275])
            #assert(len(codeword_times) == len(codeword_times_force_value))

        return codewords, codeword_times
```

to
 ```python
return codewords, codeword_times_force_value
```

(in `zi_hdawg_pb_handler`).

**Comment by huanyanqi** [comment]
Notes about the bug:
- The bug appears when we have 2 DIO changes happening at the same timestep. However, this only happens for specific decimal values of time as the bug is caused by floating point errors when converting decimal times to the DIO discrete timesteps. 
- There are 2 pathways for discretizing (one using PB_sample and one inside the ZI_HDAWG_handler) that do different things and lead to different results. The bug appears when one path says that two DIO changes happen at the same timestep while another says that they are at different times, leading to different DIO-value list length. There are also cases where there is no error but the compiled code generates 2 separate setDIO commands consecutively, corresponding to turning on each line sequentially
- Example of buggy code. Note that changing the first offset to 0, 0.1, or 0.2 has no error, although 0.1 and 0.2 generate two consecutive setDIO commands

`{
    "name": "op",
    "dur": 2.3e-06,
    "timestamp": "20-Jul-2021_14_55_20",
    "var_dict": {},
    "pulse_specifiers_dicts": [
        {
            "pulsetype": "PTrue",
            "channel": "device1",
            "is_analog": false,
            "dur": 2.0,
            "offset": "0.3",
            "tref": "After Previous Pulse",
            "pulse_vars": {
                "offset_var": 0.0,
                "dur_var": 0.0
            },
            "name": "DIO Pulse"
        },
        {
            "pulsetype": "PTrue",
            "channel": "mirror",
            "is_analog": false,
            "dur": "0.1",
            "offset": 0.0,
            "tref": "With Previous Pulse",
            "pulse_vars": {
                "offset_var": 0.0,
                "dur_var": 0.0
            },
            "name": "DIO Pulse"
        }
    ]
}`
